### Users

GET http://127.0.0.1:8000/api/users/

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json
{
    "email": "vpupkin@yandex.ru",
    "username": "vasya.pupkin",
    "first_name": "Вася",
    "last_name": "Пупкин",
    "password": "Diman_231282"
}

###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json
{
    "email": "vpupkin@yandex.ru",
    "username": "vasya.pupkin",
    "password": "Diman_231282"
}



#### Рецепты
# Список рецептов
GET http://127.0.0.1:8000/api/recipes/

###
GET http://127.0.0.1:8000/api/recipes/1/

###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json

{
    "ingredients": [
        {
            "id": 10,
            "amount": 10            
        }
    ],
    "tags": [],
    "image": null,
    "name": "рецепт-2",
    "text": "описание-3",
    "cooking_time": 3,
    "author": 1
}


###

PATCH http://127.0.0.1:8000/recipes/1/
Content-Type: application/json

{
    "name": "блюдо-2",
    "text": "описание блюда-2 обновлено"
}

###

PUT http://127.0.0.1:8000/recipes/1/
Content-Type: application/json

{
    "name": "блюдо-3",
    "text": "описание блюда-3 обновлено"
}

###

DELETE http://127.0.0.1:8000/api/recipes/28/


### Ингредиенты
GET http://127.0.0.1:8000/ingredients/
